# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'vc.ru' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vc.ru
  pod 'NeedleFoundation'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
